### ISSUE TITLE
Electron or nodeJS app (windows and or other OS)

### ISSUE THREAD

**Issue by weekendkoder** [Megabyteceer/thing-editor#15]
Hi,

I tried to make it by my own, but i failed. Would it be possible, that you guys just upload an release-app for windows users maybe ?
This would be like Christmas for me :-)

**Comment by weekendkoder** [comment]
I see you did some updates.
What about now to make a electronApp or NW.js App for Windows / MacOS / Linux / etc.
Would help many people to get access to your pixi game editor !

**Comment by Megabyteceer** [comment]
I thought to make installer, but main problem is how to integrate ffmpeg libs, without license problems. I saw i cant distribute ffmpeg, but maybe im wrong. It is really intetrsting to make instsller, in closest days i going to check if electron can utilize more memory that chrome does. If test will be successful, its will be more reasons to go to electron.
By the way, have you tried to install editor with command line provided in readme? Is there any errors?

**Comment by Megabyteceer** [comment]
Also i have to finish to fill all hrefs in editors wiki first. About 130 links is empty for now, and lead to root of document. Not wery good to distribute editor with such a problem.

**Comment by weekendkoder** [comment]
Hey ... thx for the fast respond. I can just tell you that many use electron or NW.js , like: Cocos Creator, Rogue Engine, NunuStudio, Phaser Editor 2D. They all use the favourite electron / NW for building their Game-Editor . And all of these builds have "ffmpeg.dll" inside. So seems like its legal and free. Try it out for yourself. Maybe you can find some hints.

**Comment by weekendkoder** [comment]
"By the way, have you tried to install editor with command line provided in readme? Is there any errors?"
Nope ... not yet. I guess i didnt figured out how to do it. If i am honest, i am the generation that just want a download & start App, i guess.

"Also i have to finish to fill all hrefs in editors wiki first. About 130 links is empty for now, and lead to root of document. Not wery good to distribute editor with such a problem."
Okay, i can understand this. Sometimes it is okay to give some kind of "alpha" / "beta" release out to curious people. With the comments that it is in early stage and contains errors. Something like this. Its a personal preference of handling the own software.

**Comment by Megabyteceer** [comment]
Hi. Good news. I finally made application for windows10 64bit. You can download it here https://pixel-cave.com/thing-editor-releases/thing-editor-0.1-win64.zip

**Comment by weekendkoder** [comment]
Wow ! This is amazing ! I was waiting for years to got a working app of your editor. Now it happened. I will test it out, in the evening, when i am back home. Thank you, Sir.

**Comment by Megabyteceer** [comment]
I have to say, it is still no any polished example projects yet. In archive two projects, the empty one, with one minimal scene, and another one, where just bunch of test scenes i made for my internal test and purposes. It is not mean i have no games made on thing-editor. I have 4 my own games made on editor listed here: https://pixel-cave.com/
Also we use it at my main job and released about 30 games already. So editor is very useful and polished. : )
Examples is next step after i know someone can run it on his own. : )

**Comment by weekendkoder** [comment]
Btw. nice games on Pixel-Cave.

I tried to run the editor, but it didn´t work. Maybe i done something wrong.
I execute "run.bat". Then i opend a browser, with: http://localhost:32023/ . But then i saw only this inside the browser:
>Cannot GET /

Hm, what do you think ?

**Comment by Megabyteceer** [comment]
run.bat should open editor as application automatically. You don't need to run browser. I think it is an error in bat, and windows closes it immediately so you don't see what is wrong. Please try to open commandline (*cmd*), cd to folder with run.bat, and execute *run.bat* as command line. It should keep console visible on any error. And send me any text console will show.

**Comment by Megabyteceer** [comment]
UPD: i just got the same error. Correct url is http://127.0.0.1:32023/thing-editor/

**Comment by weekendkoder** [comment]
some competitor to nodeJS :
https://neutralino.js.org/ 

It is just 2-3mb big !!!

**Comment by Megabyteceer** [comment]
Hi weekendkoder, thank you.
Editor ported to electron.js already.
I just released Electron version of editor. Build for widows: https://pixel-cave.com/thing-editor-win10-64-2.0b.zip
I have no time to test and make builds for other platforms. There is instruction how to install and run editor on linux and mac in readme file.
