### ISSUE TITLE
Frame animation

### ISSUE THREAD

**Issue by MatsMaker** [Megabyteceer/thing-editor#26]
It is a great job. Look nice!

But, how I can use [frame animations](https://pixijs.download/dev/docs/PIXI.AnimatedSprite.html)?

And I don't understand how to use many tilemaps if we can add only one preprocessor to a project.

Thanks

**Comment by Megabyteceer** [comment]
Hi Mats. Thank you!
I have never use FrameAnimation. You can add it in to components (classes) list as a custom compinent. Click New in Classes window. Enter class name MyFrameAnimation. Choose Container as a base class. Then change base class in generated js file to FrameAnimation. So this new component should appear in classes list. Double click other classes to see how add editable fields, like "image" of Sprite class, to pass it as a texture to "texture" property. And how to add editable fields which will allow you to edit other props of AF class.

For process different tilemaps i usually name them by their purposes, like "bg", "ladders", check name of selected tilemap and choose way to process it.

Another way - use one tilemap as "master" with chema only, whuch make unvisible in runtime. edit its tiles, and fill other tilemaps as a additional layers automatically. Sorry i cant provide examples today. If you need additional explanations or examples - let me know.

**Comment by MatsMaker** [comment]
Thx

I see [update](https://github.com/Megabyteceer/thing-editor/wiki/Custom-Components#update) methods don't have deltaTime
How I can get it to my custom GamObject?

I see now only one way to by edit game engine and spread this dt.
https://i.imgur.com/Grf4OTa.png

**Comment by MatsMaker** [comment]
> Hi Mats. Thank you!
> I have never use FrameAnimation. You can add it in to components (classes) list as a custom compinent. Click New in Classes window. Enter class name MyFrameAnimation. Choose Container as a base class. Then change base class in generated js file to FrameAnimation. So this new component should appear in classes list. Double click other classes to see how add editable fields, like "image" of Sprite class, to pass it as a texture to "texture" property. And how to add editable fields which will allow you to edit other props of AF class.
> 
> For process different tilemaps i usually name them by their purposes, like "bg", "ladders", check name of selected tilemap and choose way to process it.
> 
> Another way - use one tilemap as "master" with chema only, whuch make unvisible in runtime. edit its tiles, and fill other tilemaps as a additional layers automatically. Sorry i cant provide examples today. If you need additional explanations or examples - let me know.

**Comment by MatsMaker** [comment]
Thx

I see update methods don't have deltaTime
How I can get it to my custom GamObject?

I see now only two ways from game.pixiApp.ticker.deltaTime
and to by edit game engine and spread this dt.
https://i.imgur.com/Grf4OTa.png It more eases way to use

**Comment by Megabyteceer** [comment]
I use fixed time updates only. if FPS will be lower that 60, update will be called more that once to keep game speed the same.
If you want to use dt, you can subscribe you custom componemt to pixi timer with your own dtUpdate method.

**Comment by MatsMaker** [comment]
it is good way )

but PIXIjs on tick cb also sends deltaTime. And for use PIXI.AnimatedSprite I need to send it DT to PIXI.AnimatedSprite.update
And need add skip method https://i.imgur.com/sdqhAI7.png

If sent dt to GO.update we can make it just `update(dt) {super.update(dt)} and less` it mo clear. 

Or no?

**Comment by Megabyteceer** [comment]
Update calls is fixed to 60fps. So you can use 1000/60  (maybe 1/60) as fixed deltatime.
Tomorrow i will try to make custom component from AnimationFrame and send it you.

**Comment by MatsMaker** [comment]
it will be good

**Comment by Megabyteceer** [comment]
Hi Mats. I Have checked AnimatedSprite, and looks like its could be replaced easily with MovieClip.
I have made the short video to show you how to use it. https://youtu.be/ASgPjizA2vs
AnimatedSprite uses banch of textures setted at constructor time. Movie-clip could have any order of images and can have 'labels' to switch between many animations. Also MovieClip could have animation of any other properties like scale, pivot, skew, x, y, xSpeed, ySpeed. "image" property - its just one of the fields you can animate in way you want.

For now I not see the fast way how to make AnimationSprite animation editable.

**Comment by MatsMaker** [comment]
It is work. But it is bad idea ))

We use frames animations from json. I have to make scatch [there file](https://github.com/MatsMaker/thing-editor/blob/main/src/game-objects/animated-sprite.js), [all project example](https://github.com/MatsMaker/thing-editor/tree/main )

**Comment by Megabyteceer** [comment]
Ok. I think your realization is fine.
One fix - line 107.  Use 0.01666666666667  (1/60) constant instead of deltaTime. Because current realization will work with faster speed in case of low FPS. The same constant I use in Spine component .
And good luck with your project. Let me know if you will need any help.

**Comment by MatsMaker** [comment]
Thx
