### ISSUE TITLE
lib.js Uncaught TypeError

### ISSUE THREAD

**Issue by mithenji** [Megabyteceer/thing-editor#39]
<img width="995" alt="image" src="https://user-images.githubusercontent.com/3282991/190594425-8d19157c-480a-4726-b661-23b239f398dc.png">

`
Uncaught TypeError: Cannot read properties of null (reading 'Spine')
    at lib.js:247:36
    at Container.forAllChildren (container.js:120:3)
    at Game.forAllChildrenEverywhere (game.js:1332:14)
    at lib.js:246:11
`

**Comment by Megabyteceer** [comment]
Hi **mithenji** do you have any steps to reproduce it? When this error happens? Which browser do you use?
Maybe you have added any unknown type or .json, .xml, or .atlas files in project folder?
