### ISSUE TITLE
Issue with start on MacOSX

### ISSUE THREAD

**Issue by muraviovvladimir** [Megabyteceer/thing-editor#4]
>node --inspect index.js
Debugger listening on ws://127.0.0.1:9229/f481ece5-8579-47c1-8539-2b7d881bfc2c
For help, see: https://nodejs.org/en/docs/inspector
Thing-editor listening on port 32023!
(node:49833) UnhandledPromiseRejectionWarning: Error: Exited with code 1
    at ChildProcess.<anonymous> (/Users/user/game_editor_here/thing-editor/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:291:20)
    at ChildProcess.emit (events.js:203:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:203:13)
    at Pipe.<anonymous> (net.js:588:12)
(node:49833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Megabyteceer** [comment]
Hi Vladimir, thank you for report. I did not test editor on mac for a long time. Have you installed ffmpeg library? And check if ffmpeg command works in terminal. I will try to add handling for this error with tips tomorrow.

**Comment by Megabyteceer** [comment]
Also it is maybe bacause no google chrome installed.

**Comment by Megabyteceer** [comment]
I just checked editor on Mac and it is can not open Chrome via "opn" automatically.
I will try to find fix, but for now need open [http://127.0.0.1:32023/thing-editor](http://127.0.0.1:32023/thing-editor) in chrome

**Comment by muraviovvladimir** [comment]
I have installed ffmpeg & Google Chrome as an default browser

**Comment by muraviovvladimir** [comment]
> I just checked editor on Mac and it is can not open Chrome via "opn" automatically.
> I will try to find fix, but for now need open http://127.0.0.1:32023/thing-editor in chrome

And yes it works! :) Thanks guys!

**Comment by Megabyteceer** [comment]
Great. Thank you! : )
I added task to use ffmpeg npm to avoid ffmpeg installation, and will fix chrome launching on mac.
