### ISSUE TITLE
Fix install command in readme 

### ISSUE THREAD

**Issue by mterczynski** [Megabyteceer/thing-editor#59]
`npm -i` is not a valid npm command, did you meant to write `npm i`?

**Comment by Megabyteceer** [comment]
Does not it works as is? On windows it is works fine.

**Comment by mterczynski** [comment]
Tested on Windows's cmd with npm version 10.7.0:

![image](https://github.com/user-attachments/assets/747912ea-ccb0-4a75-ad46-843b1cdc0cec)

**Comment by Megabyteceer** [comment]
Fixed. Thank you a lot.
