### ISSUE TITLE
I was not able of installing it.

### ISSUE THREAD

**Issue by mrender** [Megabyteceer/thing-editor#6]
I followed all the steps but it gave me only an empty screen. These are the errors that appeared on the CONSOLE:

127.0.0.1/:1 
Refused to apply style from 'http://127.0.0.1:32023/thing-editor/css/lib/reset.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

react.production.min.js:10
Uncaught ReferenceError: require is not defined
    at react.production.min.js:10

react-dom.production.min.js:13
Uncaught ReferenceError: require is not defined
    at react-dom.production.min.js:13

tip.js:7
Uncaught ReferenceError: React is not defined
    at tip.js:7

127.0.0.1/:1
Refused to apply style from 'http://127.0.0.1:32023/thing-editor/css/lib/reset.css' because its MIME type ('text/html') is not a supported

**Comment by Megabyteceer** [comment]
Have you launched installation with admin rights? Looks like no symlinks for files were created.

**Comment by mrender** [comment]
Tried again overwriting the files and did not work again. 
Deleted everything and made a fresh install!
Now it works!!
I came here as soon as I saw it working!
I am getting back there now to try it!! 
Thank you, man! 
Keep up with the good work! ;)

**Comment by Megabyteceer** [comment]
Great. : )
I just added automatic admin access reqest for windows (mac does not need it to create symlinks). Maybe its did work out for you. Have you install it on windows?

**Comment by mrender** [comment]
Yes! Windows 10.

**Comment by Megabyteceer** [comment]
It is good news : ) installation does not needs admin rights anymore. I have updated readme file.

**Comment by Megabyteceer** [comment]
Hi, here is zip with app which will run with no any installations at all.
Windows 10 64bit build: https://pixel-cave.com/game_editor_win10_64_github.zip

**Comment by xeoshow** [comment]
Hi @Megabyteceer ,

I am also trying to setup thing-editor on my windows 10 64bit env by git cloning, but failed. and seems below link also failed ...

Could you please check? Thanks a lot.

> Hi, here is zip with app which will run with no any installations at all. Windows 10 64bit build: https://pixel-cave.com/thing-editor-releases/thing-editor-0.1-win64.zip

**Comment by Megabyteceer** [comment]
Hi @xeoshow i fixed the link.
https://pixel-cave.com/game_editor_win10_64_github.zip

By the way. Now i made ThingEditor 2.0 with Electron and typescript. It is pushed to the branch for now. zip i provided is old js version.

**Comment by xeoshow** [comment]
Great thanks!


> Hi @xeoshow i fixed the link. https://pixel-cave.com/game_editor_win10_64_github.zip
> 
> By the way. Now i made ThingEditor 2.0 with Electron and typescript. It is pushed to the branch for now. zip i provided is old js version.
