### ISSUE TITLE
How to create new project?

### ISSUE THREAD

**Issue by sergaks** [Megabyteceer/thing-editor#8]
Hi Vasiliy,
Thanks for really amazing thing!
Maybe I missed it in documentation, what is the right way to get started with new (empty) project? 

Sergei.

**Comment by Megabyteceer** [comment]
Hi Sergei, for now its no New project button in editor. I just planning to add it, but first i have to make a few useful templates for new projects. For now you can copy **thing-project-example** folder inside games folder and use it as new project. Project`s title and other settings stored in thing-project.json
Let me know if you need any help.
